# fly.toml app configuration file generated for sv-datingapp on 2023-07-09T12:06:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml file generated for da-course on 2022-11-18T12:14:21+07:00

app = "sv-datingapp"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "sourvad/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="di6t9a3z3"
  CloudinarySettings__ApiKey="655444269643422"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"